services:
  mediaarchivistbot:
    build: .
    image: ghcr.io/netherquartz/mediaarchivistbot:latest
    container_name: mediaarchivistbot
    restart: unless-stopped
    environment:
      - TG_TOKEN
      - LOGGING_LEVEL
      - POSTGRES_HOST
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - MISTRAL_API_KEY
      - OLLAMA_HOST
    mem_limit: 200m
    volumes:
    - type: tmpfs
      target: /ramdisk
      tmpfs:
        size: 200m
